(async()=>{
const $=id=>document.getElementById(id),svg=$('plot'),zMetric=$('zMetric'),colorDimension=$('colorDimension'),colorMode=$('colorMode'),planeToggle=$('planeToggle'),planeLabel=$('planeLabel'),idToggle=$('idToggle'),detail=$('detail'),list=$('systemList'),pointPopup=$('pointPopup'),axisXTitle=$('axisXTitle'),axisYTitle=$('axisYTitle'),axisZTitle=$('axisZTitle');
const NS='http://www.w3.org/2000/svg';
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else{if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}const h=rows.shift();return rows.filter(r=>r.some(v=>v!=='')).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
let records;try{const r=await fetch('data/systems.csv',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);records=parseCSV(await r.text())}catch(err){detail.innerHTML='<strong>Data could not be loaded</strong><p class="hint">The visualization reads <code>data/systems.csv</code>.</p>';console.error(err);return}
const S=records.map(r=>({id:r.system_id,brand:r.brand,listName:r.list_name,name:r.display_name,body:r.body,lens:r.lens,tc:r.teleconverter,actualFl:+r.actual_focal_length_mm,actualF:+r.actual_f_stop,fl:+r.equiv_focal_length_mm,fstop:+r.equiv_f_stop,weight:+r.system_weight_g/1000,price:+r.system_price_chf,priceDate:r.price_checked_date}));
const DIMS={fl:{label:'Equivalent focal length',axis:'35mm-equiv. focal length',better:'high'},fstop:{label:'Equivalent f-stop',axis:'35mm-equiv. f-stop',better:'low'},weight:{label:'System weight',axis:'System weight',better:'low'},price:{label:'System price',axis:'System price',better:'low'}};
const ext=a=>[Math.min(...a),Math.max(...a)],R={};Object.keys(DIMS).forEach(d=>R[d]=ext(S.map(s=>s[d])));
const priceFmt=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}),priceExact=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',minimumFractionDigits:2,maximumFractionDigits:2});
const nrm=(v,d)=>(v-R[d][0])/(R[d][1]-R[d][0])*2-1,denrm=(v,d)=>(v+1)/2*(R[d][1]-R[d][0])+R[d][0];
function visible(){return ['fl','fstop',zMetric.value]}function sizeMetric(){return zMetric.value==='weight'?'price':'weight'}function coords(s){return[nrm(s.fl,'fl'),nrm(s.fstop,'fstop'),nrm(s[zMetric.value],zMetric.value)]}
function solve(A,b){const n=A.length,m=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;[m[c],m[p]]=[m[p],m[c]];const d=m[c][c];if(Math.abs(d)<1e-12)throw new Error('Singular regression matrix');for(let j=c;j<=n;j++)m[c][j]/=d;for(let r=0;r<n;r++)if(r!==c){const f=m[r][c];for(let j=c;j<=n;j++)m[r][j]-=f*m[c][j]}}return m.map(r=>r[n])}
function fit(dep,preds){const p=preds.length,n=p+1,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const s of S){const x=[1,...preds.map(k=>s[k])],y=s[dep];for(let i=0;i<n;i++){b[i]+=x[i]*y;for(let j=0;j<n;j++)A[i][j]+=x[i]*x[j]}}return{dep,preds,coef:solve(A,b)}}
let currentModel,currentResidualMax=1,planePreference=true;function rebuildModel(){const dep=colorDimension.value,v=visible(),preds=v.includes(dep)?v.filter(d=>d!==dep):v;currentModel=fit(dep,preds);currentResidualMax=Math.max(...S.map(s=>Math.abs(residual(s))))||1;const drawable=preds.length===2&&v.includes(dep);planeToggle.disabled=!drawable;planeToggle.checked=drawable?planePreference:false;planeLabel.textContent=drawable?'Average plane':'Average plane unavailable for size dimension'}function expected(s){return currentModel.coef[0]+currentModel.preds.reduce((a,p,i)=>a+currentModel.coef[i+1]*s[p],0)}function residual(s){return s[currentModel.dep]-expected(s)}
function fmt(v,d,dec=2){if(d==='fl')return`${Math.round(v)} mm`;if(d==='fstop')return`f/${(+v.toFixed(dec)).toString()}`;if(d==='weight')return`${v.toFixed(dec)} kg`;return priceFmt.format(v)}function fmtResidual(v,d){const sign=v>0?'+':'';if(d==='fl')return`${sign}${Math.round(v)} mm`;if(d==='fstop')return`${sign}${v.toFixed(2)} f-number`;if(d==='weight')return`${sign}${v.toFixed(2)} kg`;return`${sign}${priceFmt.format(v)}`}
function greenRed(t){t=Math.max(0,Math.min(1,t));return`hsl(${120*(1-t)} 78% 43%)`}function pointColor(s){const d=colorDimension.value,info=DIMS[d];let q;if(colorMode.value==='absolute')q=(s[d]-R[d][0])/(R[d][1]-R[d][0]);else q=(residual(s)+currentResidualMax)/(2*currentResidualMax);return greenRed(info.better==='high'?1-q:q)}function radius(s){const d=sizeMetric(),q=(s[d]-R[d][0])/(R[d][1]-R[d][0]);return 7+13*q}
let yaw=-38*Math.PI/180,pitch=24*Math.PI/180,zoom=1,selected=null,pointerState=null,activePreset='custom';
function project([x,y,z]){const cy=Math.cos(yaw),sy=Math.sin(yaw),x1=x*cy-z*sy,z1=x*sy+z*cy,cp=Math.cos(pitch),sp=Math.sin(pitch),y1=y*cp-z1*sp,z2=y*sp+z1*cp,sc=215*zoom;return[450+x1*sc,325-y1*sc,z2]}
const mk=(tag,a={},p=svg)=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);p.appendChild(e);return e},tx=(x,y,t,a={},p=svg)=>{const e=mk('text',{x,y,fill:'var(--text)','font-size':'11',...a},p);e.textContent=t;return e},line=(a,b,g,more={})=>{const A=project(a),B=project(b);mk('line',{x1:A[0],y1:A[1],x2:B[0],y2:B[1],stroke:'var(--grid)','stroke-width':'1.15',...more},g)};
function uniqueObserved(d){return[...new Set(S.map(s=>s[d]))].sort((a,b)=>a-b)}function downsample(a,n){if(a.length<=n)return a;const out=[];for(let i=0;i<n;i++)out.push(a[Math.round(i*(a.length-1)/(n-1))]);return[...new Set(out)]}function linearTicks(d,n=5){const[a,b]=R[d];return Array.from({length:n},(_,i)=>a+(b-a)*i/(n-1))}
function axes(g){const c=[[-1,-1,-1],[1,-1,-1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,-1,1],[-1,1,1],[1,1,1]];[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]].forEach(([a,b])=>line(c[a],c[b],g));[-.5,0,.5].forEach(t=>{line([t,-1,-1],[t,1,-1],g,{opacity:.22});line([-1,t,-1],[1,t,-1],g,{opacity:.22});line([-1,-1,t],[-1,1,t],g,{opacity:.16})});downsample(uniqueObserved('fl'),6).forEach(v=>{const p=project([nrm(v,'fl'),-1,-1]);tx(p[0],p[1]+17,fmt(v,'fl'),{'text-anchor':'middle',fill:'var(--muted)','font-size':'10'},g)});downsample(uniqueObserved('fstop'),9).forEach(v=>{const p=project([-1,nrm(v,'fstop'),-1]);tx(p[0]-8,p[1]+3,fmt(v,'fstop'),{'text-anchor':'end',fill:'var(--muted)','font-size':'10'},g)});linearTicks(zMetric.value,5).forEach(v=>{const p=project([-1,-1,nrm(v,zMetric.value)]);tx(p[0]-8,p[1]+3,fmt(v,zMetric.value,1),{'text-anchor':'end',fill:'var(--muted)','font-size':'10'},g)})}
const cube=[[-1,-1,-1],[1,-1,-1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,-1,1],[-1,1,1],[1,1,1]],edges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];
function rawFromQ(q){return{fl:denrm(q[0],'fl'),fstop:denrm(q[1],'fstop'),[zMetric.value]:denrm(q[2],zMetric.value)}}function planeFn(q){const s=rawFromQ(q);return s[currentModel.dep]-(currentModel.coef[0]+currentModel.preds.reduce((a,p,i)=>a+currentModel.coef[i+1]*s[p],0))}
function drawPlane(g){
  if(!planeToggle.checked||planeToggle.disabled)return;
  const pts=[],add=q=>{if(!pts.some(p=>Math.hypot(p[0]-q[0],p[1]-q[1],p[2]-q[2])<1e-6))pts.push(q)};
  for(const[ia,ib]of edges){
    const A=cube[ia],B=cube[ib],ga=planeFn(A),gb=planeFn(B);
    if(Math.abs(ga)<1e-9)add(A);
    if(Math.abs(gb)<1e-9)add(B);
    if(ga*gb<0){const t=ga/(ga-gb);add([A[0]+t*(B[0]-A[0]),A[1]+t*(B[1]-A[1]),A[2]+t*(B[2]-A[2])])}
  }
  if(pts.length<3)return;
  const pp=pts.map(project),cx=pp.reduce((a,p)=>a+p[0],0)/pp.length,cy=pp.reduce((a,p)=>a+p[1],0)/pp.length;
  pp.sort((a,b)=>Math.atan2(a[1]-cy,a[0]-cx)-Math.atan2(b[1]-cy,b[0]-cx));
  mk('polygon',{points:pp.map(p=>`${p[0]},${p[1]}`).join(' '),fill:'var(--plane)','fill-opacity':'.16',stroke:'var(--plane)','stroke-width':'1.7','stroke-dasharray':'7 5','pointer-events':'none'},g)
}
function setAxisPos(el,pos){el.className=`axis-title pos-${pos}`}function updateAxisTitles(){axisXTitle.textContent=DIMS.fl.axis;axisYTitle.textContent=DIMS.fstop.axis;axisZTitle.textContent=DIMS[zMetric.value].axis;axisXTitle.hidden=axisYTitle.hidden=axisZTitle.hidden=false;setAxisPos(axisXTitle,'bottom');setAxisPos(axisYTitle,'left');setAxisPos(axisZTitle,'right');if(activePreset==='reach-aperture')axisZTitle.hidden=true;else if(activePreset==='reach-z')axisYTitle.hidden=true;else if(activePreset==='aperture-z'){axisXTitle.hidden=true;setAxisPos(axisZTitle,'bottom');setAxisPos(axisYTitle,'left')}}
function updatePresetButtons(){document.querySelector('[data-view="reach-z"]').textContent=`Reach × ${zMetric.value}`;document.querySelector('[data-view="aperture-z"]').textContent=`Aperture × ${zMetric.value}`;document.querySelectorAll('.viewbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===activePreset));updateAxisTitles()}
function usePreset(v){activePreset=v;if(v==='reach-aperture'){yaw=0;pitch=0}else if(v==='reach-z'){yaw=0;pitch=Math.PI/2}else if(v==='aperture-z'){yaw=Math.PI/2;pitch=0}updatePresetButtons();render()}
function updateSizeLegend(){const d=sizeMetric();$('sizeNote').textContent=`${DIMS[d].label}. When Z is ${DIMS[zMetric.value].label.toLowerCase()}, point size automatically shows ${DIMS[d].label.toLowerCase()}.`;$('sizeScale').innerHTML=`<span>${fmt(R[d][0],d,1)}</span><span>${fmt(R[d][1],d,1)}</span>`}
function updateLegend(){const d=colorDimension.value,info=DIMS[d],res=colorMode.value==='residual';$('legendTitle').textContent=`${info.label} — ${res?'efficiency residual':'absolute'}`;if(!res){const lo=R[d][0],hi=R[d][1],mid=(lo+hi)/2,vals=info.better==='high'?[hi,mid,lo]:[lo,mid,hi];$('scale').innerHTML=vals.map(v=>`<span>${fmt(v,d,1)}</span>`).join('');$('legendNote').textContent=`Greener = ${d==='fl'?'longer reach':d==='fstop'?'faster/lower equivalent f-number':d==='weight'?'lighter system':'lower price'}.`;return}const left=info.better==='high'?currentResidualMax:-currentResidualMax,right=-left;$('scale').innerHTML=`<span>${fmtResidual(left,d)}</span><span>0</span><span>${fmtResidual(right,d)}</span>`;const pred=currentModel.preds.map(p=>DIMS[p].label.toLowerCase()).join(' + ');$('legendNote').textContent=`Efficiency residual: greener = ${d==='fl'?'longer':d==='fstop'?'faster/lower':d==='weight'?'lighter':'cheaper'} than predicted from ${pred}. This is not an absolute-performance ranking.`}
function updatePopup(){if(selected===null){pointPopup.hidden=true;return}const s=S[selected],d=colorDimension.value,p=project(coords(s));pointPopup.hidden=false;pointPopup.style.left=`${(p[0]/900)*100}%`;pointPopup.style.top=`${(p[1]/650)*100}%`;pointPopup.dataset.side=p[0]>620?'left':'right';pointPopup.innerHTML=`<strong>${s.listName}</strong><span>${Math.round(s.fl)} mm equiv · f/${s.fstop} equiv · ${s.weight.toFixed(3)} kg · ${priceFmt.format(s.price)}</span><br><span class="muted">${DIMS[d].label} residual: ${fmtResidual(residual(s),d)}</span>`}
function resetDetail(){detail.innerHTML='<strong>Select a system</strong><p class="hint">Click any point or system below.</p>'}function select(i){selected=i;const s=S[i],d=colorDimension.value;detail.innerHTML=`<strong>${s.listName}</strong><div class="hint">${s.body}</div><dl class="detail"><dt>Equivalent FL</dt><dd>${Math.round(s.fl)} mm</dd><dt>Equivalent f-stop</dt><dd>f/${s.fstop}</dd><dt>Actual FL</dt><dd>${s.actualFl} mm</dd><dt>Actual f-stop</dt><dd>f/${s.actualF}</dd><dt>Weight</dt><dd>${s.weight.toFixed(3)} kg</dd><dt>Price snapshot</dt><dd>${priceExact.format(s.price)}</dd><dt>${DIMS[d].label} expected</dt><dd>${fmt(expected(s),d,2)}</dd><dt>${DIMS[d].label} residual</dt><dd>${fmtResidual(residual(s),d)}</dd></dl>`;updateRows();render()}function clearSelection(){selected=null;resetDetail();updateRows();render()}
function render(){svg.innerHTML='';const g=mk('g');axes(g);drawPlane(g);S.map((s,i)=>({s,i,p:project(coords(s))})).sort((a,b)=>a.p[2]-b.p[2]).forEach(({s,i,p})=>{const r=radius(s),grp=mk('g',{tabindex:'0',role:'button','data-point-index':String(i),'aria-label':`${i+1}. ${s.listName}`},g);mk('circle',{cx:p[0],cy:p[1],r:selected===i?r+3:r,fill:pointColor(s),stroke:selected===i?'var(--text)':'rgba(255,255,255,.92)','stroke-width':selected===i?'2.8':'1.3',style:'cursor:pointer'},grp);if(idToggle.checked)tx(p[0],p[1]+3.5,String(i+1),{'font-size':'9','font-weight':'700','text-anchor':'middle',fill:'#111','pointer-events':'none'},grp);grp.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(i)}})});updatePopup()}
function buildList(){list.innerHTML='';const by=new Map();S.forEach((s,i)=>{if(!by.has(s.brand))by.set(s.brand,[]);by.get(s.brand).push(i)});[...by.keys()].sort((a,b)=>a.localeCompare(b)).forEach(brand=>{const group=document.createElement('section');group.className='brandgroup';const title=document.createElement('div');title.className='brandtitle';title.textContent=brand;const head=document.createElement('div');head.className='systemhead';head.innerHTML='<span>ID</span><span>Brand + lens (teleconverter)</span><span>Body</span><span style="text-align:right">Eq. FL</span><span style="text-align:right">Eq. f</span><span style="text-align:right">Weight</span><span style="text-align:right">Price</span>';group.append(title,head);by.get(brand).sort((a,b)=>S[a].listName.localeCompare(S[b].listName)||S[a].body.localeCompare(S[b].body)).forEach(i=>{const s=S[i],b=document.createElement('button');b.type='button';b.dataset.i=i;b.className='systemrow';b.innerHTML=`<span class="sys-id"><span class="dot" style="width:11px;height:11px;background:${pointColor(s)}"></span>${i+1}</span><span class="sys-name">${s.listName}<span class="sys-body">${s.body}</span></span><span class="sys-bodycol">${s.body.replace(/^Canon EOS |^Sony Alpha |^Fujifilm |^OM System |^Nikon /,'')}</span><span class="sys-num sys-fl">${Math.round(s.fl)} mm</span><span class="sys-num sys-f">f/${s.fstop}</span><span class="sys-num sys-weight">${s.weight.toFixed(3)} kg</span><span class="sys-price">${priceFmt.format(s.price)}</span>`;b.addEventListener('click',()=>select(i));group.appendChild(b)});list.appendChild(group)})}
function updateRows(){list.querySelectorAll('.systemrow').forEach(b=>{const i=+b.dataset.i;b.classList.toggle('active',i===selected);const d=b.querySelector('.dot');if(d)d.style.background=pointColor(S[i])})}
function refresh(){rebuildModel();updateSizeLegend();updateLegend();updatePresetButtons();updateRows();render()}
zMetric.addEventListener('change',()=>{rebuildModel();updateSizeLegend();updatePresetButtons();updateLegend();updateRows();render()});colorDimension.addEventListener('change',()=>{rebuildModel();updateLegend();updateRows();render()});colorMode.addEventListener('change',()=>{updateLegend();updateRows();render()});planeToggle.addEventListener('change',()=>{if(!planeToggle.disabled)planePreference=planeToggle.checked;render()});idToggle.addEventListener('change',render);$('clearSelection').addEventListener('click',clearSelection);document.querySelectorAll('.viewbtn').forEach(b=>b.addEventListener('click',()=>usePreset(b.dataset.view)));
svg.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;const hit=e.target.closest?.('[data-point-index]');pointerState={id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,dragging:false,pointIndex:hit?+hit.getAttribute('data-point-index'):null}});svg.addEventListener('pointermove',e=>{const p=pointerState;if(!p||e.pointerId!==p.id)return;const moved=Math.hypot(e.clientX-p.startX,e.clientY-p.startY);if(!p.dragging&&moved>5){p.dragging=true;activePreset='custom';updatePresetButtons();try{svg.setPointerCapture(e.pointerId)}catch(_){}}if(!p.dragging)return;const dx=e.clientX-p.lastX,dy=e.clientY-p.lastY;p.lastX=e.clientX;p.lastY=e.clientY;yaw+=dx*.01;pitch=Math.max(-1.48,Math.min(1.48,pitch+dy*.008));render()});svg.addEventListener('pointerup',e=>{const p=pointerState;if(!p||e.pointerId!==p.id)return;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);pointerState=null;if(!p.dragging){if(Number.isInteger(p.pointIndex))select(p.pointIndex);else clearSelection()}});svg.addEventListener('pointercancel',e=>{if(pointerState&&e.pointerId===pointerState.id)pointerState=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId)});svg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(1.5,zoom*(e.deltaY>0?.94:1.06)));activePreset='custom';updatePresetButtons();render()},{passive:false});
colorDimension.value='weight';rebuildModel();buildList();refresh();
})();
