(async()=>{
const $=id=>document.getElementById(id), svg=$('plot'),comparisonMode=$('comparisonMode'),axisX=$('axisX'),axisY=$('axisY'),axisZ=$('axisZ'),axisZWrap=$('axisZWrap'),colorDimension=$('colorDimension'),colorMode=$('colorMode'),planeToggle=$('planeToggle'),planeLabel=$('planeLabel'),idToggle=$('idToggle'),detail=$('detail'),list=$('systemList'),pointPopup=$('pointPopup'),viewMeta=$('viewMeta'),axisXTitle=$('axisXTitle'),axisYTitle=$('axisYTitle'),axisZTitle=$('axisZTitle'),interactionHint=$('interactionHint');
const NS='http://www.w3.org/2000/svg';
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else{if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}const headers=rows.shift();return rows.filter(r=>r.some(v=>v!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
let records;try{const response=await fetch('data/systems.csv',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);records=parseCSV(await response.text());}catch(err){detail.innerHTML='<strong>Data could not be loaded</strong><p class="hint">The visualization reads <code>data/systems.csv</code>.</p>';console.error(err);return;}
const S=records.map(r=>({id:r.system_id,brand:r.brand,listName:r.list_name,name:r.display_name,body:r.body,lens:r.lens,tc:r.teleconverter,actualFl:+r.actual_focal_length_mm,actualF:+r.actual_f_stop,fl:+r.equiv_focal_length_mm,f:+r.equiv_f_stop,w:+r.system_weight_g/1000,price:+r.system_price_chf,priceDate:r.price_checked_date}));
const DIMS={fl:{key:'fl',label:'Equivalent focal length',axis:'35mm-equiv. focal length',better:'high'},fstop:{key:'f',label:'Equivalent f-stop',axis:'35mm-equiv. f-stop',better:'low'},weight:{key:'w',label:'System weight',axis:'System weight',better:'low'},price:{key:'price',label:'System price',axis:'System price',better:'low'}};
const ORDER=['fl','fstop','weight','price'];const val=(s,d)=>s[DIMS[d].key], ext=a=>[Math.min(...a),Math.max(...a)];const R=Object.fromEntries(ORDER.map(d=>[d,ext(S.map(s=>val(s,d)))]));
const priceFmt=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0});const priceFmtExact=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',minimumFractionDigits:2,maximumFractionDigits:2});
function fillAxis(sel){sel.innerHTML=ORDER.map(d=>`<option value="${d}">${DIMS[d].label}</option>`).join('');} [axisX,axisY,axisZ].forEach(fillAxis);axisX.value='fl';axisY.value='fstop';axisZ.value='weight';
let yaw=-38*Math.PI/180,pitch=24*Math.PI/180,zoom=1,selected=null,pointerState=null,currentModel=null,currentResidualMax=1;
const mk=(tag,a={},p=svg)=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);p.appendChild(e);return e};const tx=(x,y,s,a={},p=svg)=>{const e=mk('text',{x,y,fill:'var(--text)','font-size':'11',...a},p);e.textContent=s;return e};
const norm=(v,d)=>(v-R[d][0])/(R[d][1]-R[d][0])*2-1, denorm=(n,d)=>(n+1)/2*(R[d][1]-R[d][0])+R[d][0];
function mode(){return comparisonMode.value} function axes(){return mode()==='2d'?[axisX.value,axisY.value]:[axisX.value,axisY.value,axisZ.value]} function fourthDim(){return ORDER.find(d=>!axes().includes(d))||'price'} function activeDims(){return mode()==='4d'?[...axes(),fourthDim()]:axes();}
function ensureUnique(){const sels=mode()==='2d'?[axisX,axisY]:[axisX,axisY,axisZ];const used=[];for(const s of sels){if(used.includes(s.value)){s.value=ORDER.find(d=>!used.includes(d))||s.value;}used.push(s.value);}}
function syncColorOptions(){const active=activeDims(),old=colorDimension.value;colorDimension.innerHTML=active.map(d=>`<option value="${d}">${DIMS[d].label}</option>`).join('');colorDimension.value=active.includes(old)?old:(active.includes('weight')?'weight':active[0]);}
function solve(A,b){const n=A.length,m=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;[m[c],m[p]]=[m[p],m[c]];const q=m[c][c];if(Math.abs(q)<1e-12)throw Error('Singular regression');for(let j=c;j<=n;j++)m[c][j]/=q;for(let r=0;r<n;r++)if(r!==c){const f=m[r][c];for(let j=c;j<=n;j++)m[r][j]-=f*m[c][j];}}return m.map(r=>r[n]);}
function fit(dep,preds){const k=preds.length+1,A=Array.from({length:k},()=>Array(k).fill(0)),b=Array(k).fill(0);for(const s of S){const x=[1,...preds.map(p=>val(s,p))],y=val(s,dep);for(let i=0;i<k;i++){b[i]+=x[i]*y;for(let j=0;j<k;j++)A[i][j]+=x[i]*x[j];}}return{dep,preds,coef:solve(A,b)}}
function expected(s,model=currentModel){const x=[1,...model.preds.map(p=>val(s,p))];return model.coef.reduce((a,c,i)=>a+c*x[i],0)} function residual(s){return val(s,currentModel.dep)-expected(s)}
function rebuildModel(){const dep=colorDimension.value,preds=activeDims().filter(d=>d!==dep);currentModel=fit(dep,preds);currentResidualMax=Math.max(...S.map(s=>Math.abs(residual(s))))||1;}
function greenRed(t){t=Math.max(0,Math.min(1,t));return `hsl(${120*(1-t)} 78% 43%)`} function absoluteNorm(s,d){return(val(s,d)-R[d][0])/(R[d][1]-R[d][0])} function pointColor(s){const d=colorDimension.value,info=DIMS[d];if(colorMode.value==='absolute'){const q=absoluteNorm(s,d);return greenRed(info.better==='high'?1-q:q)}const q=(residual(s)+currentResidualMax)/(2*currentResidualMax);return greenRed(info.better==='high'?1-q:q)}
function fmt(v,d,dec=2){if(d==='price')return priceFmt.format(v);if(d==='weight')return `${v.toFixed(dec)} kg`;if(d==='fl')return `${Math.round(v)} mm`;return `f/${(+v.toFixed(dec))}`} function fmtResidual(v,d){const sign=v>0?'+':'';if(d==='price')return `${sign}${priceFmt.format(v)}`;if(d==='weight')return `${sign}${v.toFixed(2)} kg`;if(d==='fl')return `${sign}${Math.round(v)} mm`;return `${sign}${v.toFixed(2)} f-number`}
function radius(s){if(mode()==='2d')return selected!==null&&S[selected]===s?12:9;const d=mode()==='4d'?fourthDim():'weight',q=(val(s,d)-R[d][0])/(R[d][1]-R[d][0]);return 7+13*q}
function coords(s){const a=axes();return [norm(val(s,a[0]),a[0]),norm(val(s,a[1]),a[1]),mode()==='2d'?0:norm(val(s,a[2]),a[2])]}
function project3(q){const[x,y,z]=q,cy=Math.cos(yaw),sy=Math.sin(yaw),x1=x*cy-z*sy,z1=x*sy+z*cy,cp=Math.cos(pitch),sp=Math.sin(pitch),y1=y*cp-z1*sp,z2=y*sp+z1*cp,sc=215*zoom;return[450+x1*sc,320-y1*sc,z2]}
function project2(q){return[100+(q[0]+1)/2*700,565-(q[1]+1)/2*480,0]} function project(q){return mode()==='2d'?project2(q):project3(q)} function line(a,b,g,more={}){const A=project(a),B=project(b);mk('line',{x1:A[0],y1:A[1],x2:B[0],y2:B[1],stroke:'var(--grid)','stroke-width':'1.15',...more},g)}
function uniqueObserved(d){return[...new Set(S.map(s=>val(s,d)))].sort((a,b)=>a-b)} function downsample(vals,max){if(vals.length<=max)return vals;const out=[];for(let i=0;i<max;i++)out.push(vals[Math.round(i*(vals.length-1)/(max-1))]);return[...new Set(out)]}
function ticks(d){if(d==='fstop')return downsample(uniqueObserved(d),9);if(d==='fl')return downsample(uniqueObserved(d),7);if(d==='weight'){const a=[R[d][0],2,2.5,3,3.5,4,R[d][1]].filter(v=>v>=R[d][0]&&v<=R[d][1]);return[...new Set(a)]}const lo=R.price[0],hi=R.price[1],base=[lo,5000,10000,15000,20000,hi].filter(v=>v>=lo&&v<=hi);return[...new Set(base)]}
function tickText(v,d){if(d==='price')return priceFmt.format(v).replace('CHF ','CHF ');if(d==='weight')return `${+v.toFixed(2)}kg`;if(d==='fl')return `${Math.round(v)}`;return `f/${+v.toFixed(2)}`}
function drawAxes2(g){const[xd,yd]=axes();line([-1,-1,0],[1,-1,0],g,{'stroke-width':'1.6'});line([-1,-1,0],[-1,1,0],g,{'stroke-width':'1.6'});line([1,-1,0],[1,1,0],g,{opacity:.28});line([-1,1,0],[1,1,0],g,{opacity:.28});ticks(xd).forEach(v=>{const p=project2([norm(v,xd),-1,0]);tx(p[0],p[1]+22,tickText(v,xd),{'text-anchor':'middle',fill:'var(--muted)','font-size':'10'},g)});ticks(yd).forEach(v=>{const p=project2([-1,norm(v,yd),0]);tx(p[0]-10,p[1]+4,tickText(v,yd),{'text-anchor':'end',fill:'var(--muted)','font-size':'10'},g)});}
function drawAxes3(g){const[a,b,c]=axes(),C=[[-1,-1,-1],[1,-1,-1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,-1,1],[-1,1,1],[1,1,1]],E=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];E.forEach(([i,j])=>line(C[i],C[j],g));[-.5,0,.5].forEach(t=>{line([t,-1,-1],[t,1,-1],g,{opacity:.18});line([-1,t,-1],[1,t,-1],g,{opacity:.18});line([-1,-1,t],[-1,1,t],g,{opacity:.13})});ticks(a).forEach(v=>{const p=project3([norm(v,a),-1,-1]);tx(p[0],p[1]+17,tickText(v,a),{'text-anchor':'middle',fill:'var(--muted)','font-size':'9.5'},g)});ticks(b).forEach(v=>{const p=project3([-1,norm(v,b),-1]);tx(p[0]-8,p[1]+4,tickText(v,b),{'text-anchor':'end',fill:'var(--muted)','font-size':'9.5'},g)});ticks(c).forEach(v=>{const p=project3([-1,-1,norm(v,c)]);tx(p[0]-8,p[1]+4,tickText(v,c),{'text-anchor':'end',fill:'var(--muted)','font-size':'9.5'},g)});}
function rawFromQ(q){const a=axes();return Object.fromEntries(a.map((d,i)=>[d,denorm(q[i],d)]))} const cubeCorners=[[-1,-1,-1],[1,-1,-1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,-1,1],[-1,1,1],[1,1,1]],cubeEdges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];
function planeFn(q){const dep=currentModel.dep,raw=rawFromQ(q),observed=raw[dep],pred=currentModel.coef[0]+currentModel.preds.reduce((a,p,i)=>a+currentModel.coef[i+1]*raw[p],0);return observed-pred}
function drawPlane3(g){if(!planeToggle.checked||mode()!=='3d')return;const pts=[],add=q=>{if(!pts.some(p=>Math.hypot(p[0]-q[0],p[1]-q[1],p[2]-q[2])<1e-6))pts.push(q)};cubeEdges.forEach(([ia,ib])=>{const A=cubeCorners[ia],B=cubeCorners[ib],ga=planeFn(A),gb=planeFn(B);if(Math.abs(ga)<1e-9)add(A);if(Math.abs(gb)<1e-9)add(B);if(ga*gb<0){const t=ga/(ga-gb);add([A[0]+t*(B[0]-A[0]),A[1]+t*(B[1]-A[1]),A[2]+t*(B[2]-A[2])])}});if(pts.length<3)return;const pp=pts.map(q=>project3(q)),cx=pp.reduce((a,p)=>a+p[0],0)/pp.length,cy=pp.reduce((a,p)=>a+p[1],0)/pp.length;pp.sort((a,b)=>Math.atan2(a[1]-cy,a[0]-cx)-Math.atan2(b[1]-cy,b[0]-cx));mk('polygon',{points:pp.map(p=>`${p[0]},${p[1]}`).join(' '),fill:'var(--plane)','fill-opacity':'.16',stroke:'var(--plane)','stroke-width':'1.7','stroke-dasharray':'7 5','pointer-events':'none'},g)}
function drawTrend2(g){if(!planeToggle.checked||mode()!=='2d')return;const dep=currentModel.dep,pred=currentModel.preds[0],[xd,yd]=axes();const p0=R[pred][0],p1=R[pred][1],f=v=>currentModel.coef[0]+currentModel.coef[1]*v;let A,B;if(dep===xd){A=[norm(f(p0),xd),norm(p0,yd),0];B=[norm(f(p1),xd),norm(p1,yd),0]}else{A=[norm(p0,xd),norm(f(p0),yd),0];B=[norm(p1,xd),norm(f(p1),yd),0]}line(A,B,g,{stroke:'var(--plane)','stroke-width':'2','stroke-dasharray':'7 5'})}
function updateViewMeta(){const a=axes(),m=mode();const pills=[`Mode: ${m==='4d'?'Experimental 4D':m.toUpperCase()}`,`X: ${DIMS[a[0]].label}`,`Y: ${DIMS[a[1]].label}`];if(m!=='2d')pills.push(`Z: ${DIMS[a[2]].label}`);if(m==='4d')pills.push(`Size / 4th dimension: ${DIMS[fourthDim()].label}`);viewMeta.innerHTML=pills.map((x,i)=>`<span class="view-pill ${m==='4d'&&i===0?'experimental':''}">${x}</span>`).join('');axisXTitle.textContent=DIMS[a[0]].axis;axisYTitle.textContent=DIMS[a[1]].axis;axisZTitle.textContent='';axisZTitle.hidden=true;axisXTitle.hidden=m!=='2d';axisYTitle.hidden=m!=='2d';$('resetView').disabled=m==='2d';interactionHint.textContent=m==='2d'?'2D comparison · click a point to inspect. Switch back to 3D or 4D for rotation.':'Drag to rotate · wheel/trackpad to zoom · click a point to inspect.';}
function updatePlaneControl(){if(mode()==='2d'){planeLabel.textContent='Average trend line';planeToggle.disabled=false}else if(mode()==='3d'){planeLabel.textContent='Average plane';planeToggle.disabled=false}else{planeLabel.textContent='4D hyperplane (not drawable)';planeToggle.disabled=true}}
function updateSizeLegend(){const d=mode()==='4d'?fourthDim():(mode()==='3d'?'weight':null);$('sizeTitle').textContent=mode()==='4d'?'4th dimension / point size':'Point size';if(!d){$('sizeNote').textContent='Constant in 2D mode.';$('sizeScale').innerHTML='<span>same size</span><span></span>';return}$('sizeNote').textContent=`${DIMS[d].label}${mode()==='4d'?' (the fourth dimension)':''}`;$('sizeScale').innerHTML=`<span>${fmt(R[d][0],d,1)}</span><span>${fmt(R[d][1],d,1)}</span>`}
function updateLegend(){const d=colorDimension.value,info=DIMS[d],res=colorMode.value==='residual';$('legendTitle').textContent=`${info.label} — ${res?'efficiency residual':'absolute'}`;if(!res){const lo=R[d][0],hi=R[d][1],mid=(lo+hi)/2,ordered=info.better==='high'?[hi,mid,lo]:[lo,mid,hi];$('scale').innerHTML=ordered.map(v=>`<span>${fmt(v,d,1)}</span>`).join('');$('legendNote').textContent=`Greener = ${d==='fl'?'longer reach':d==='fstop'?'faster/lower equivalent f-number':d==='weight'?'lighter system':'lower price'}.`;return}const left=info.better==='high'?currentResidualMax:-currentResidualMax,right=-left;$('scale').innerHTML=`<span>${fmtResidual(left,d)}</span><span>0</span><span>${fmtResidual(right,d)}</span>`;const pred=currentModel.preds.map(p=>DIMS[p].label.toLowerCase()).join(' + ');$('legendNote').textContent=`Efficiency residual: greener = ${d==='fl'?'longer':d==='fstop'?'faster/lower':d==='weight'?'lighter':'cheaper'} than predicted from ${pred}. This is not an absolute-performance ranking.`;}
function updatePointPopup(){if(selected===null){pointPopup.hidden=true;return}const s=S[selected],d=colorDimension.value,rv=residual(s),p=project(coords(s));pointPopup.hidden=false;pointPopup.style.left=`${(p[0]/900)*100}%`;pointPopup.style.top=`${(p[1]/650)*100}%`;pointPopup.dataset.side=p[0]>620?'left':'right';pointPopup.innerHTML=`<strong>${s.listName}</strong><span>${Math.round(s.fl)} mm equiv · f/${s.f} equiv · ${s.w.toFixed(3)} kg · ${priceFmt.format(s.price)}</span><br><span class="muted">${DIMS[d].label} residual: ${fmtResidual(rv,d)}</span>`}
function resetDetail(){detail.innerHTML='<strong>Select a system</strong><p class="hint">Click any point or system below.</p>'}
function select(i){selected=i;const s=S[i],d=colorDimension.value,ev=expected(s),rv=residual(s);detail.innerHTML=`<strong>${s.listName}</strong><div class="hint">${s.body}</div><dl class="detail"><dt>Equivalent FL</dt><dd>${Math.round(s.fl)} mm</dd><dt>Equivalent f-stop</dt><dd>f/${s.f}</dd><dt>Actual FL</dt><dd>${s.actualFl} mm</dd><dt>Actual f-stop</dt><dd>f/${s.actualF}</dd><dt>Weight</dt><dd>${s.w.toFixed(3)} kg</dd><dt>Price snapshot</dt><dd>${priceFmtExact.format(s.price)}</dd><dt>${DIMS[d].label} expected</dt><dd>${fmt(ev,d,2)}</dd><dt>${DIMS[d].label} residual</dt><dd>${fmtResidual(rv,d)}</dd></dl>`;updateButtons();render()}
function clearSelection(){selected=null;resetDetail();updateButtons();render()}
function render(){svg.innerHTML='';const g=mk('g');if(mode()==='2d'){drawAxes2(g);drawTrend2(g)}else{drawAxes3(g);drawPlane3(g)}S.map((s,i)=>({s,i,p:project(coords(s))})).sort((a,b)=>a.p[2]-b.p[2]).forEach(({s,i,p})=>{const r=radius(s),grp=mk('g',{tabindex:'0',role:'button','data-point-index':String(i),'aria-label':`${i+1}. ${s.listName}`},g);mk('circle',{cx:p[0],cy:p[1],r:selected===i?r+3:r,fill:pointColor(s),stroke:selected===i?'var(--text)':'rgba(255,255,255,.92)','stroke-width':selected===i?'2.8':'1.3',style:'cursor:pointer'},grp);if(idToggle.checked)tx(p[0],p[1]+3.5,String(i+1),{'font-size':'9','font-weight':'700','text-anchor':'middle',fill:'#111','pointer-events':'none'},grp);grp.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(i)}})});updatePointPopup()}
function buildList(){list.innerHTML='';const byBrand=new Map();S.forEach((s,i)=>{if(!byBrand.has(s.brand))byBrand.set(s.brand,[]);byBrand.get(s.brand).push(i)});[...byBrand.keys()].sort((a,b)=>a.localeCompare(b)).forEach(brand=>{const group=document.createElement('section');group.className='brandgroup';const title=document.createElement('div');title.className='brandtitle';title.textContent=brand;const head=document.createElement('div');head.className='systemhead';head.innerHTML='<span>ID</span><span>Brand + lens (teleconverter)</span><span>Body</span><span style="text-align:right">Eq. FL</span><span style="text-align:right">Eq. f</span><span style="text-align:right">Weight</span><span style="text-align:right">Price</span>';group.append(title,head);byBrand.get(brand).sort((ia,ib)=>S[ia].listName.localeCompare(S[ib].listName)||S[ia].body.localeCompare(S[ib].body)).forEach(i=>{const s=S[i],b=document.createElement('button');b.type='button';b.dataset.i=i;b.className='systemrow';const d=11;b.innerHTML=`<span class="sys-id"><span class="dot" style="width:${d}px;height:${d}px;background:${pointColor(s)}"></span>${i+1}</span><span class="sys-name">${s.listName}<span class="sys-body">${s.body}</span></span><span class="sys-bodycol">${s.body.replace(/^Canon EOS |^Sony Alpha |^Fujifilm |^OM System |^Nikon /,'')}</span><span class="sys-num sys-fl">${Math.round(s.fl)} mm</span><span class="sys-num sys-f">f/${s.f}</span><span class="sys-num sys-weight">${s.w.toFixed(3)} kg</span><span class="sys-price">${priceFmt.format(s.price)}</span>`;b.addEventListener('click',()=>select(i));group.appendChild(b)});list.appendChild(group)})}
function updateButtons(){list.querySelectorAll('.systemrow').forEach(b=>{const i=+b.dataset.i;b.classList.toggle('active',i===selected);const dot=b.querySelector('.dot');if(dot)dot.style.background=pointColor(S[i])})}
function syncAll(){ensureUnique();axisZWrap.hidden=mode()==='2d';syncColorOptions();rebuildModel();updatePlaneControl();updateViewMeta();updateSizeLegend();updateLegend();updateButtons();render()}
comparisonMode.addEventListener('change',()=>{if(mode()==='4d'){axisX.value='fl';axisY.value='fstop';axisZ.value='weight'}yaw=-38*Math.PI/180;pitch=24*Math.PI/180;zoom=1;syncAll()});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const map={'reach-aperture':['fl','fstop'],'reach-weight':['fl','weight'],'aperture-weight':['fstop','weight'],'reach-price':['fl','price']},a=map[b.dataset.preset];comparisonMode.value='2d';axisX.value=a[0];axisY.value=a[1];yaw=-38*Math.PI/180;pitch=24*Math.PI/180;zoom=1;syncAll()}));[axisX,axisY,axisZ].forEach(s=>s.addEventListener('change',syncAll));colorDimension.addEventListener('change',()=>{rebuildModel();updateLegend();updateButtons();render()});colorMode.addEventListener('change',()=>{updateLegend();updateButtons();render()});[planeToggle,idToggle].forEach(e=>e.addEventListener('change',render));$('clearSelection').addEventListener('click',clearSelection);$('resetView').addEventListener('click',()=>{yaw=-38*Math.PI/180;pitch=24*Math.PI/180;zoom=1;render()});
svg.addEventListener('pointerdown',e=>{if(mode()==='2d')return;if(e.button!==undefined&&e.button!==0)return;const hit=e.target.closest?.('[data-point-index]');pointerState={id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,dragging:false,pointIndex:hit?+hit.getAttribute('data-point-index'):null}});svg.addEventListener('pointermove',e=>{const p=pointerState;if(!p||e.pointerId!==p.id)return;const moved=Math.hypot(e.clientX-p.startX,e.clientY-p.startY);if(!p.dragging&&moved>5){p.dragging=true;try{svg.setPointerCapture(e.pointerId)}catch(_){}}if(!p.dragging)return;const dx=e.clientX-p.lastX,dy=e.clientY-p.lastY;p.lastX=e.clientX;p.lastY=e.clientY;yaw+=dx*.01;pitch=Math.max(-1.48,Math.min(1.48,pitch+dy*.008));render()});svg.addEventListener('pointerup',e=>{const p=pointerState;if(!p||e.pointerId!==p.id)return;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);pointerState=null;if(!p.dragging&&Number.isInteger(p.pointIndex))select(p.pointIndex)});svg.addEventListener('pointercancel',e=>{if(pointerState&&e.pointerId===pointerState.id)pointerState=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId)});svg.addEventListener('click',e=>{if(mode()!=='2d')return;const hit=e.target.closest?.('[data-point-index]');if(hit)select(+hit.getAttribute('data-point-index'))});svg.addEventListener('wheel',e=>{if(mode()==='2d')return;e.preventDefault();zoom=Math.max(.65,Math.min(1.5,zoom*(e.deltaY>0?.94:1.06)));render()},{passive:false});
fillAxis(axisX);fillAxis(axisY);fillAxis(axisZ);axisX.value='fl';axisY.value='fstop';axisZ.value='weight';syncColorOptions();colorDimension.value='weight';rebuildModel();buildList();syncAll();
})();
